name: Snap Build

#on:
#  push:
#    branches:
#      - novos-testes

on:
  pull_request: # Triggers the workflow on pull requests targeting the main branch
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main # Whenever a commit is pushed to main
    tags:
      - 'v*' # Whenever a new version tag is pushed

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v4
      - name: Install Snapcraft and setup LXD
        id: prepare-env
        run: |
          sudo iptables -P FORWARD ACCEPT
          sudo snap install --channel stable --classic snapcraft
          sudo snap install lxd
          sudo lxd init --auto
          sudo usermod -aG lxd $USER
      - name: Build snap and prepare the artifact for upload
        id: build-snap
        run: |
          newgrp lxd <<EOB
            snapcraft
          EOB
          SNAP_FILE=$(ls ./*.snap | head -n 1)
          echo "snap=$SNAP_FILE" >> $GITHUB_OUTPUT
      - name: Upload snap artifact locally
        id: upload-snap
        uses: actions/upload-artifact@v4
        with:
          name: esc-komatsu-ptxd-snap
          path: ${{ steps.build-snap.outputs.snap }}
      - name: Publish to Snap Store (edge)
        uses: snapcore/action-publish@v1
        env:
            SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
        with:
          snap: ${{ steps.build-snap.outputs.snap }}
          release: edge
  promote-to-candidate:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Promote edge to candidate
        uses: snapcrafters/ci/release-to-candidate@v1
        with:
          repo-token: ${{ secrets.SNAP_STORE_LOGIN }}
          store-token: ${{ secrets.SNAP_STORE_LOGIN }}
          channel: candidate
          snapcraft-channel: edge

  release-to-stable:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Promote candidate to stable
        uses: snapcrafters/ci/promote-to-stable@v1
        with:
          store-token: ${{ secrets.SNAP_STORE_LOGIN }}
          channel: stable
          snapcraft-channel: candidate
