name: Snap Build

on:
  pull_request: # Triggers the workflow on pull requests targeting the main branch
    types: [opened, synchronize, reopened, closed]


permissions:
  contents: read

jobs:
  build-and-publish:
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v4
      - name: Install Snapcraft and setup LXD
        id: prepare-env
        run: |
          sudo iptables -P FORWARD ACCEPT
          sudo snap install --channel stable --classic snapcraft
          sudo snap install lxd
          sudo lxd init --auto
          sudo usermod -aG lxd $USER
      - name: Build snap and prepare the artifact for upload
        id: build-snap
        run: |
          newgrp lxd <<EOB
            snapcraft
          EOB
          SNAP_FILE=$(ls ./*.snap | head -n 1)
          echo "snap=$SNAP_FILE" >> $GITHUB_OUTPUT
      - name: Upload snap artifact locally
        id: upload-snap
        uses: actions/upload-artifact@v4
        with:
          name: esc-komatsu-ptxd-snap
          path: ${{ steps.build-snap.outputs.snap }}
      - name: Publish to Snap Store (edge)
        uses: snapcore/action-publish@v1
        env:
            SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
        with:
          snap: ${{ steps.build-snap.outputs.snap }}
          release: edge
