name: Promote RC \u2192 candidate

on:
  push:
    tags:
      - 'v*-rc*'

jobs:
  promote-rc:
    if: startsWith(github.ref, 'refs/tags/v') && contains(github.ref, '-rc')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Parse snapcraft.yaml
        id: snapcraft-yaml
        uses: snapcrafters/ci/parse-snapcraft-yaml@main
      - name: Install Snapcraft
        run: sudo snap install snapcraft --classic --channel=stable
      - name: Promote snap from edge -> candidate
        run: |
          REV=$(snapcraft list-revisions ${{ steps.snapcraft-yaml.outputs.snap-name }} | awk '/edge/{print $1; exit}')
          snapcraft release ${{ steps.snapcraft-yaml.outputs.snap-name }} $REV candidate
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}


