name: Promote to stable on PR merge

on:
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  promote-stable:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Parse snapcraft.yaml
        id: snapcraft-yaml
        uses: snapcrafters/ci/parse-snapcraft-yaml@main
      - name: Find last RC tag
        id: find-last-rc
        run: |
          TAG=$(git tag --list 'v*-rc*' --sort=-v:refname | head -n1)
          if [ -z "$TAG" ]; then
            echo "No RC tag found, skipping."
            exit 0
          fi
          STABLE_TAG=$(echo "$TAG" | sed -E 's/-rc[0-9]+$//')
          echo "rc_tag=$TAG" >> $GITHUB_OUTPUT
          echo "stable_tag=$STABLE_TAG" >> $GITHUB_OUTPUT
      - name: Create and push stable tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag ${{ steps.find-last-rc.outputs.stable_tag }}
          git push origin ${{ steps.find-last-rc.outputs.stable_tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.find-last-rc.outputs.stable_tag }}
          name: "Release ${{ steps.find-last-rc.outputs.stable_tag }}"
          body: Automatic release promoted from ${{ steps.find-last-rc.outputs.rc_tag }}.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Snapcraft
        run: sudo snap install snapcraft --classic --channel=stable
      - name: Promote snap from candidate -> stable
        run: |
          REV=$(snapcraft list-revisions ${{ steps.snapcraft-yaml.outputs.snap-name }} | awk '/candidate/{print $1; exit}')
          snapcraft release ${{ steps.snapcraft-yaml.outputs.snap-name }} $REV stable
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}